version: '3'

volumes:
  txt_db:
    name: api_bank_okd_txt

services:
  okd_api_bank:
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    container_name: okd_api_bank
    image: mikesave/api_bank_okd:10
    restart: always
    volumes:
      - txt_db:/app/data
